[phases.setup]
nixPkgs = ["php82", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "composer install",
    "python3 -m ensurepip",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm install && npm run build",
    "chmod +x ai/food_recommendation.py"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"