[phases.setup]
nixPkgs = ["php", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["composer install", "python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"