[phases.setup]
nixPkgs = ["php82", "python311", "python311Packages.pip", "nodejs"]

[phases.install]
cmds = [
    "composer install",
    "python3 -m venv /app/venv",
    "/app/venv/bin/pip install --upgrade pip",
    "/app/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm install && npm run build",
    "chmod +x ai/food_recommendation.py"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"