[phases.setup]
nixPkgs = ["php82", "python311", "python311Packages.pip", "nodejs"]

[phases.install]
cmds = [
    "composer install",
    "pip install --upgrade pip --break-system-packages",
    "pip install -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
    "npm install && npm run build",
    "chmod +x ai/food_recommendation.py"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"