[phases.setup]
nixPkgs = ["php", "python311", "python311Packages.pip", "python311Packages.pandas", "python311Packages.numpy"]

[phases.install]
cmds = ["composer install", "python3 -m pip install -r requirements.txt"]